---
# handlers file for ansible-elasticsearch
- name: start es
  become: yes
  service: name="{{ es_service_name }}" state=started

- name: restart es
  become: yes
  service: name="{{ es_service_name }}" state=restarted
  
- name: stop es
  become: yes
  service: name="{{ es_service_name }}" state=stopped